on: push
jobs:
    npm-build:
        name: npm-build工作
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - run: cd vue_admin
        - run: pwd
        - run: ls -l
        - run: npm --version
        - run: npm install
        - run: npm run build

