on: push
jobs:
    npm-build:
        name: npm-build工作
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: ./
        steps:
        - uses: actions/checkout@v4   
        - run: pwd
        - run: ls -l           
        - run: npm --version
        - run: npm install --force
        - run: npm run build

      
        - uses: JamesIves/github-pages-deploy-action@v4
          with: 
            branch: gh-pages
            folder: build
            
