on: push
jobs:
    npm-build:
        name: npm-build工作
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: ./
        steps:
        - uses: actions/checkout@v4   
        - run: pwd
        - run: ls -l           
        - run: npm --version
        - run: npm install
        - run: npm run build
            
